modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LGPLv3"

[[mods]] #mandatory
	modId="fakename" #mandatory
	version="${file.jarVersion}" #mandatory
	displayName="Fakename" #mandatory
	logoFile="logo.png" #optional
	authors="Tschipp" #optional
	# The description text for the mod (multi line!) (#mandatory)
	description="Fakename adds a way to change the name of players."
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.fakename]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[32.0.106,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.fakename]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
